#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Bring in secrets if they exist
if [[ -s "$HOME/.zsecrets" ]]; then
    source "$HOME/.zsecrets"
fi

# Allow keybindings in menu completion
zstyle ':completion:*' menu select
zmodload zsh/complist

# Bring in keybindings
if [[ -s "${ZDOTDIR:-$HOME}/keys.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/keys.zsh"
fi

# -- PYENV
export PYENV_ROOT="$HOME/.pyenv" 
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"


# -- JENV
 export PATH="$HOME/.jenv/bin:$PATH"
 eval "$(jenv init -)"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
